### PR TITLE
POI at 19 zoom

### PR DESCRIPTION
**Pull request by RLRR**
Map don't requests POI at 19 zoom.

Projects:
- Santiago
- Lemesos
- Lefkosia

### CODE REVIEW

**Comment by Trufi** [comment]
:+1:

**Comment by ilfa** [comment]
:+1:

**Comment by ilfa** [comment]
For test try this POI http://2gis.cl/santiago/query/jos%C3%A9%20francisco%20vergara%2C%20274/geo/14215418332054818/center/-70.733516%2C-33.367376/zoom/19

**Comment by andymost** [comment]
That example i think better http://2gis.cl/santiago/center/-70.6624022126198%2C-33.444717/zoom/18
Because gallery poi callouts have behavior like building callouts.

**Comment by andymost** [comment]
Sorry, incorrect url http://2gis.cl/santiago/callout/-70.662601%2C-33.445278%2Cbranch-70000001007393380/center/-70.662528%2C-33.44533/zoom/19

**Pull request merged**
