### PR TITLE
Incorrect bound parsing when region.bounds contains more than five points

### PR DESCRIPTION
**Pull request by RLRR**
New region data has regions with bounds that contain more than five points.
We parse those bounds incorrectly.

### CODE REVIEW

**Comment by RLRR** [comment]
WKT bound parser now constructs a rectangular bound that contains all points in WKT polygon.

**Comment by ilfa** [comment]
:+1:

**Comment by Trufi** [comment]
:+1:

**Comment by fobos** [comment]
:+1:

**Pull request merged**
