### PR TITLE
Improve test connections

### PR DESCRIPTION
**Pull request by andymost**
- Add options in setScripts to disable animation
 - Add commented config for run test from JenkinsCI on vmmaster
 - Remove unnecessary space in mailto link

### CODE REVIEW

**Comment by Trufi** [comment]
Зачем два одинаковых коммита? Может засквошишь?

**Comment by andymost** [comment]
@Trufi  done

**Comment by Trufi** [comment]
:+1:

**Comment by RLRR** [comment]
:+1:

**Pull request merged**
